
name: start-preview

on:
  push:
    branches-ignore: [ "main", "master" ]

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.4.1
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"
      - uses: sergeysova/jq-action@v2
      - name: Get lightdash version 
        id: version 
        run: curl -s https://eu1.lightdash.cloud/api/v1/health  | jq -r '.results.version'
      - name: Show my version
        run: 'echo "version ${{ steps.version.outputs.value }}"'
      - name: Copy profiles.yml
        env:
          config: ${{ secrets.DBT_PROFILES }}          
        run: echo -e "$config" > profiles.yml      

      - name: Install dbt
        run: pip install dbt-core dbt-postgres dbt-redshift dbt-snowflake dbt-bigquery

      - name: Install lightdash CLI
        run: npm install -g "@lightdash/cli@${{ steps.version.outputs.value }}" || npm install -g @lightdash/cli@latest

      - name: Lightdash CLI start preview 
        env:
          LIGHTDASH_API_KEY: ${{ secrets.LIGHTDASH_API_KEY }}          
          LIGHTDASH_PROJECT: ${{ secrets.LIGHTDASH_PROJECT }}          
          LIGHTDASH_URL: ${{ secrets.LIGHTDASH_URL }}          

        run:  lightdash start-preview --project-dir . --profiles-dir . --name ${GITHUB_REF##*/}


